[package]
name = "site"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
from-pest = "0.3.2"
pest_vm = "2.7.10"
pest_meta = "2.7.10"
anyhow = "1.0.84"
pest = "2.7.10"
pest_derive = "2.7.13"
trql = "0.2.1"
serde = "1.0.217"
serde_yml = "0.0.12"
remedy = { version = "0.1.0", path = "../remedy" }
